name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17', '21']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Drevision=${{ github.sha }}

  release:
    name: Publish to GitHub Packages
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
      - name: Deploy to GitHub Packages
        run: mvn -B deploy --no-transfer-progress -Drevision=${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Git tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.version.outputs.version }}
          tag_exists_error: false
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release create '${{ steps.version.outputs.version }}' -t 'openhtmltopdf ${{ steps.version.outputs.version }}' --generate-notes
